# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: delivery my server2
      env:
        db_passwd: ${{ secrets.DB_PASSWD }}
      uses: appleboy/ssh-action@master
      with:
        host: duckbo.site
        username: moneybook
        password: ${{ secrets.passwd }}
        port: 22
        script: sh /home/moneybook/run.sh ${{ secrets.DB_PASSWD }}
